In [2]:
#install a package in current environment
#!conda install -c conda-forge factor_analyzer --y
#https://factor-analyzer.readthedocs.io/en/latest/index.html
import numpy as np
import pandas as pd
from factor_analyzer import FactorAnalyzer
path = 'F:/fall-21/ime692/l4/decathlon.csv'

In [3]:
#280 scores from 1960 to 2004 for Olympic decathlon

df_features = pd.read_csv(path)
hd = list(df_features.columns.values)
hd

['100m', 'LJ', 'SP', 'HJ', '400m', '100mH', 'DS', 'PV', 'JV', '1500m']

In [5]:
fa = FactorAnalyzer(rotation='varimax', n_factors = 3, is_corr_matrix=True)
fa.fit(df_features)

FactorAnalyzer(is_corr_matrix=True, rotation='varimax', rotation_kwargs={})

In [6]:
loadings = np.round(fa.loadings_, decimals=3)
pd.DataFrame(loadings, index = hd, columns = ('factor1', 'factor2', 'factor3'))

#Factor1 - explosive arm strength
#Factor2 - explosive leg strength
#factor3 - running endurance

factor1  factor2  factor3
100m     0.223    0.978   -0.023
LJ       0.417    0.576    0.297
SP       0.891    0.264   -0.019
HJ       0.438    0.276    0.480
400m     0.112    0.498    0.502
100mH    0.302    0.271    0.154
DS       0.800    0.163    0.001
PV       0.475    0.322    0.497
JV       0.479    0.090    0.143
1500m   -0.029   -0.014    0.600

In [7]:
fa.get_factor_variance()

(array([2.40842836, 1.89474594, 1.22092451]),
 array([0.24084284, 0.18947459, 0.12209245]),
 array([0.24084284, 0.43031743, 0.55240988]))

In [8]:
fa.get_communalities()

array([1.00770588, 0.59371499, 0.86328236, 0.49780071, 0.51230271,
       0.18816799, 0.66670305, 0.5757707 , 0.25817363, 0.36047678])

In [ ]:
#-----SIMULATION EXAMPLE-----

In [1]:
import numpy as np

In [2]:
Z1 = np.random.default_rng().normal(size = 100)
Z2 = np.random.default_rng().normal(size = 100)
Z3 = np.random.default_rng().normal(size = 100)

In [3]:
X1 = Z1
X2 = X1 + Z2/100
X3 = 10*Z3

In [9]:
#PCA
#prepare the dataset
Y = np.column_stack((X1, X2)) #Y.shape
Z = np.column_stack((Y, X3))

In [10]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(Z)

PCA(n_components=2)

In [11]:
#First PCA
print(np.round(pca.components_[0], 2))

[ 0. -1. -0.]


In [12]:
#Now factor analysis
#from sklearn.decomposition import FactorAnalysis --probabilistic interpretation..
#fa = FactorAnalysis(n_components=2, random_state=0, rotation='varimax')
#fa.fit(Z)
#np.round(fa.components_[0], 2)

In [13]:
from factor_analyzer import FactorAnalyzer
fa = FactorAnalyzer(rotation='varimax', n_factors = 2)
fa.fit(Z)

FactorAnalyzer(n_factors=2, rotation='varimax', rotation_kwargs={})

In [14]:
np.round(fa.loadings_, 2)

array([[-1.  , -0.  ],
       [ 0.01,  0.09],
       [ 1.  , -0.  ]])