In [1]:
#install a package in current environment
#!conda install -c conda-forge factor_analyzer --y

import numpy as np
import pandas as pd
from factor_analyzer import FactorAnalyzer
path = 'F:/fall-20/ime692/lecture4/decathlon.csv'

In [2]:
#280 scores from 1960 to 2004 for Olympic decathlon

df_features = pd.read_csv(path)
hd = list(df_features.columns.values)
hd

['100m', 'LJ', 'SP', 'HJ', '400m', '100mH', 'DS', 'PV', 'JV', '1500m']

In [3]:
fa = FactorAnalyzer(rotation='varimax', n_factors = 3, is_corr_matrix=True)
fa.fit(df_features)

FactorAnalyzer(is_corr_matrix=True, rotation='varimax', rotation_kwargs={})

In [42]:
loadings = np.round(fa.loadings_, decimals=3)
pd.DataFrame(loadings, index = hd, columns = ('factor1', 'factor2', 'factor3'))

#Factor1 - explosive arm strength
#Factor2 - explosive leg strength
#factor3 - running endurance

factor1  factor2  factor3
100m     0.223    0.978   -0.023
LJ       0.417    0.576    0.297
SP       0.891    0.264   -0.019
HJ       0.438    0.276    0.480
400m     0.112    0.498    0.502
100mH    0.302    0.271    0.154
DS       0.800    0.163    0.001
PV       0.475    0.322    0.497
JV       0.479    0.090    0.143
1500m   -0.029   -0.014    0.600

In [45]:
fa.get_factor_variance()

(array([2.40842834, 1.89474593, 1.2209245 ]),
 array([0.24084283, 0.18947459, 0.12209245]),
 array([0.24084283, 0.43031743, 0.55240988]))

In [46]:
fa.get_uniquenesses()

array([-0.00770588,  0.406285  ,  0.13671764,  0.50219928,  0.4876973 ,
        0.81183201,  0.33329695,  0.42422931,  0.74182638,  0.63952323])

In [2]:
import unicodedata2